### PR TITLE
Use createElement instead of DOM factory for react 16 compatibility

### PR DESCRIPTION
**Pull request by vladnicula**

### CODE REVIEW

**Comment by greenimpala** [comment]
👍

**Comment by andrewcroce** [comment]
👍

**Comment by pelhage** [comment]
Yes please- upgraded to react 16 today and am having issues now

**Comment by greenimpala** [comment]
For now you can add `"reactable": "vladnicula/reactable"` to your `package.json`. This project seems dead.

**Comment by abdulrahman-khankan** [comment]
@glittershark could you please approve this? Thanks.

**Comment by Pola93** [comment]
@glittershark please approve this PR ASAP ;)

**Comment by abdulrahman-khankan** [comment]
Fixed in reactable v1.0.0, feel free to download from npm.
@Pola93 @greenimpala @pelhage @andrewcroce @vladnicula

**Comment by vladnicula** [comment]
@abdulrahman-khankan I don't see the commit in master. Last one is in November 2016. What's up with that?

**Comment by abdulrahman-khankan** [comment]
@vladnicula I took over the npm name and published a new version with a new fork repo.

**Comment by vladnicula** [comment]
Link to new repo for convenience: https://github.com/abdulrahman-khankan/reactable

**Pull request closed without merging**
