### PR TITLE
Use null rather than an empty string when not rendering filter

### LINKED ISSUE #133: Error in console: "Danger: Discarding unexpected node"
Hi,

I am getting an error in console when displaying reactable in my application. Using react 0.12.2 and reactable 0.10.1.

```
Danger: Discarding unexpected node: 
<span data-reactid=".0.1.1.0.2:$tabContents.$Interface.$table.$thead.0"></span>
...
```

I've narrowed it down to the filterer and the source code in reactable.jsx:
```
{this.props.filtering === true ?
                        <Filterer
                            colSpan={this.props.columns.length}
                            onFilter={this.props.onFilter}
                            placeholder={this.props.filterPlaceholder}
                            value={this.props.currentFilter}
                        /> : ''}
```
The problematic part is returning an empty string there, which creates the unexpected node. In my opinion way cleaner code would look like:
```
{if (this.props.filtering === true) { 
                        return <Filterer
                            colSpan={this.props.columns.length}
                            onFilter={this.props.onFilter}
                            placeholder={this.props.filterPlaceholder}
                            value={this.props.currentFilter}
                        />
}}
```
Because it does not output an empty element if the filterering is disabled. So it would also stop react from complaining.

### PR DESCRIPTION
**Pull request by glittershark**
Fixes #133

### CODE REVIEW

**Comment by cythrawll** [comment]
this didn't make it to build/reactable.js so I'm still seeing the error that this fixes.

**Comment by glittershark** [comment]
oop

**Comment by glittershark** [comment]
For the time being this should be fixed in the latest (beta) release (as of #155). Can you use that?

**Comment by cythrawll** [comment]
I think I'd rather live with the error for now unfortunately, getting ready
for a release and I don't want to introduce potential problems, but I will
keep an eye on it for next release.

**Comment by glittershark** [comment]
:+1: makes sense

**Pull request merged**
