### PR TITLE
Add onSort callback passing via props 

### PR DESCRIPTION
**Pull request by JonathanBruce**
I saw added onSort event as prop #211

And I need this functionality for my project pretty severely. So I wrote a test and updated the documentation for it under Events section. 

I'm not sure why the noDataText stuff is in there? I didn't touch that.

### CODE REVIEW

**Comment by glittershark** [comment]
Can you squash your two last commits into the first one please?

**Comment by JonathanBruce** [comment]
yeah my bad

**Comment by JonathanBruce** [comment]
Success

**Comment by glittershark** [comment]
I'm still seeing three commits here. I'd like "fixed linting errors" not to exist, and to be a part of the first one (3aac053, right now) instead

**Comment by JonathanBruce** [comment]
Ahhh I squished the two linting fixes into one, I just moved it back, on refresh it shows two commits for me

**Comment by JonathanBruce** [comment]
Understandable, done.

**Comment by JonathanBruce** [comment]
LMK if there's anything else.

**Comment by JonathanBruce** [comment]
Can this be merged? I'm currently referencing my forked repo for this functionality but I would rather just save this to the package.json to completely address the issue in my work.

**Comment by roblingle** [comment]
+1. I was looking at the solution on #134 but prefer approach. Could add onFilter, onPageChange, etc following this pattern.

**Comment by glittershark** [comment]
@roblingle I'll accept patches to add more event handler callbacks

**Comment by roblingle** [comment]
Great. Moving my edit from above:

Would an `onStateChange` be too much? Seems broad, but I'm trying to use this in Meteor and I'd need these to update the subscription. Not sure how/if others deal with tens of thousands of records for display but I'd rather only fetch what I need to show.

**Comment by glittershark** [comment]
Just pushed version 0.12.1 with this PR

**Comment by glittershark** [comment]
The problem of fetching data to display in tables lazily rather than having everything client-side is a potentially fairly hairy one. I feel like the majority of the value proposition of Reactable is in handling sorting, filtering, and pagination of data for you, and if we're just passing that responsibility off to the server then all Reactable is really doing is upper-casing the HTML tags. 

But that's just my thoughts. If you feel like there's an API for asyncronous data that you'd get some value out of here then feel free to discuss it over in #116

**Comment by roblingle** [comment]
Agreed, and I've been on the fence. It's nice to have conveniences from an existing component, but I may end up duplicating real functionality on the server for "upper-cased HTML tags".

**Pull request merged**
