### PR TITLE
updated readme with short description about paginator button labels

### PR DESCRIPTION
**Pull request by nscarcella**
https://github.com/glittershark/reactable/pull/261

### CODE REVIEW

**Comment by glittershark** [comment]
wrap to 80 chars :)

**Comment by glittershark** [comment]
but yes, thanks for this.

**Comment by glittershark** [comment]
please squash to one commit

**Comment by nscarcella** [comment]
Ok, sure. Do you mean the last 3 commits or just the README ones?

**Comment by glittershark** [comment]
sweet, thanks!

**Comment by glittershark** [comment]
Just pushed version 0.12.5, Travis should publish that to npm in the next couple minutes

**Pull request merged**
