### PR TITLE
added failing test for rendering sub components

### PR DESCRIPTION
**Pull request by growlsworth**
Hey @glittershark,

I was looking at your other bugs and you mentioned that you [like PRs with failing tests](https://github.com/glittershark/reactable/issues/122#issuecomment-76324048). So here's a failing test that addresses https://github.com/glittershark/reactable/issues/156. 

It would be awesome if you could make better headway than I did. I would also learn a little more on how React works. I got stuck when parsing the children at https://github.com/glittershark/reactable/blob/master/src/reactable/table.jsx#L64, because the sub components don't have any children.

Here's a picture of a guinea pig wearing a tiny sombrero to inspire you:

Guinea Pig Sombrero

### CODE REVIEW

**Comment by growlsworth** [comment]
Hey @glittershark,

I did a spike on a proposed solution. Overall I give it a 3/5 stars of a solution. It requires a double render which isn't great. Also, I haven't tested it in sorting/filtering/updating which is the main reason of using reactable.

I don't think this solution addresses @alfredo-cp's issue https://github.com/glittershark/reactable/issues/159.

Let me know what you think.

**Comment by glittershark** [comment]
:+1: :+1: :+1: if every FOSS contributor were like you, the world would be a better and happier place

**Comment by glittershark** [comment]
Overall this is a pretty solid PR. Tests are good, guinea pig is good.

**Comment by growlsworth** [comment]
Thanks. This was way more into the internals of React than I've ever gone. It may be possible to access sub component's children later in the component lifecycle and avoid the `getData` or additional `render` call. I mostly wanted to make sure this was possible.

**Comment by growlsworth** [comment]
Hey @glittershark, I feel like we left this conversation at an ambiguous state. Would you like me to continue down an implementation path, or would rather take the reins from here?

**Comment by jgarcia99** [comment]
@growlsworth @glittershark What approach should I take starting from scratch? These are 2 components table & row.

**Comment by jgarcia99** [comment]
```
var Row = React.createClass({

    propTypes: {
        order: React.PropTypes.object.isRequired
    },

    getDefaultProps: function() {
        return {
            order : null
        };
    },

    onClickOrder: function() {
        rspActions.selectOrder(this.props.order);
    },

    render: function() {
        if (this.props.order) {
            return (
                <tr className="order-row" onClick={this.onClickOrder} style={this.styles.order}>
                    <td>{this.props.order.timeCreated}</td>
                    <td>{this.props.order.member.firstName} {this.props.order.member.lastName}</td>
                    <td>{this.props.order.vehicle.year} {this.props.order.vehicle.make} {this.props.order.vehicle.model} ({this.props.order.vehicle.color})</td>
                    <td>{this.props.order.orderID}</td>
                    <td>{this.props.order.type}</td>
                    <td><Status status={this.props.order.status} /></td>
                </tr>
            );
        }
    }
```

**Comment by jgarcia99** [comment]
```
var Table = React.createClass({
    
    propTypes: {
        orders: React.PropTypes.arrayOf(React.PropTypes.object).isRequired
    },
    
    getDefaultProps: function() {
        return {
            orders : []
        };
    },

    render: function() {

        var orders = '';
		if (this.props.orders) {
			orders = this.props.orders.map(function(order, index){
		      return <Row order={order} />;
		    });
		}

        return (
            <div>
                <Controls />
                <Bootstrap.Table>
                    <thead style={this.styles.thead}>
                        <tr>
                            <th>Date/Time</th>
                            <th>Name</th>
                            <th>Vehicle</th>
                            <th>Order Number</th>
                            <th>Type</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody style={this.styles.tbody}>
                        {orders}
                    </tbody>
                </Bootstrap.Table>
            </div>
        );
    },
```

**Comment by jgarcia99** [comment]
I got the same errors from #159 before starting over

**Comment by aidanlister** [comment]
We've had to build our table from scratch too ... I will get our developer to post our finished table as an idea of things that we needed to be able to do.

**Comment by jgarcia99** [comment]
thanks would really appreciate it @aidanlister

**Comment by glittershark** [comment]
@growlsworth I'm pretty swamped with my day job as of late, feel free to take a crack at doing this with `render()`

**Comment by growlsworth** [comment]
Will do. Other things are prioritized for me right now, but I'll get around to completing this.

**Comment by jgarcia99** [comment]
@growlsworth You would be a savior man reactable does exactly what I need for this project

**Comment by jgarcia99** [comment]
Can you check my code out @growlsworth

**Comment by growlsworth** [comment]
Hey @glittershark , just wanted to say this is still on my radar. Priorities got shifted around at work, as they always do, so I haven't had time to put into this.

**Comment by glittershark** [comment]
@growlsworth I've got some time and would love to take a crack at this. Made any progress yet?

**Comment by growlsworth** [comment]
I have made no progress. It would be great if you could put your brain on
it. :)

**Comment by glittershark** [comment]
:+1:

**Comment by glittershark** [comment]
@growlsworth came up with the exact solution to this at 1am immediately before falling asleep, like with all good tough programming problems. That's in #196, please take a look and let me know what you think. Gonna close this PR since all of its commits are over there in one form or another

**Pull request closed without merging**
