### PR TITLE
Keep intermediate built modules around

### LINKED ISSUE #167: Issue with requiring via webpack
Error: Cannot find module './stringable

in [node_modules/reactable/build/reactable.js:95](https://github.com/glittershark/reactable/blob/master/build/reactable.js#L95).

I'm running on https://github.com/glittershark/reactable/releases/tag/0.11.0-beta2.

### PR DESCRIPTION
**Pull request by glittershark**
Rather than putting them in tmp/ and .gitignore-ing them, keep the
individually compiled ES6 modules (each of which implicitly supports
CommonJS and therefore Node and Webpack and friends due to UMD)
committed to the repo.

/cc @growlsworth, @thientran1707 can you verify that this fixes your Webpack problem?

Fixes #167

### CODE REVIEW

**Comment by thientran1707** [comment]
I got the React is not defined in React.Component line 51 in filterer.js @glittershark

**Comment by thientran1707** [comment]
I get the error React not defined in filterer.js

**Comment by glittershark** [comment]
@thientran1707 how about this?

**Comment by glittershark** [comment]
(obviously this breaks browsers, but I just want to make sure that it *does* work in CommonJS before trying to fix it)

**Comment by growlsworth** [comment]
Packaged successfully for me in my project. 

I pulled this branch to my machine and I experienced the same test failure as travis.

:+1:

**Comment by glittershark** [comment]
Nice! I'll get on making the big-ol'-concatenated-blob working, then

**Comment by thientran1707** [comment]
interesting, the next button works but previous does not...haha @glittershark but it's working now :+1:

**Pull request merged**
