### PR TITLE
pagination enhancement

### PR DESCRIPTION
**Pull request by tsargent**
- adds a previous and next button.  Previous button does not appear on first page.  Next button does not appear on last page.
- sets a limit to how many pages are shown in the paginator, with a `pageButtonLimit` prop.  Defaults to 10 if that prop isn't set.
- current page number appear as close to the middle of the set as possible, depending on how many pages are to the left and to the right.  See Google's pattern for an example.
- adds test

### CODE REVIEW

**Comment by glittershark** [comment]
Can you make the numbers here configurable? Like a `pageButtonLimit` prop?

**Comment by glittershark** [comment]
Also please add tests and squash everything into a couple related commits

**Comment by tsargent** [comment]
yes, will do...

**Comment by tsargent** [comment]
@glittershark  all set if you want to take another look.  Great component, by the way!

**Comment by cumbreras** [comment]
Hey guys, can someone bump the version in npm? (not using bower, soz) 

Thanks!

**Comment by thientran1707** [comment]
hi, how can I use the pagination? I want to change the style to bootstrap pagination. But the doc does not show how to customize the pagination

**Comment by glittershark** [comment]
Yeah, this looks good. Thanks @tsargent!

**Comment by glittershark** [comment]
@thientran1707 see #4

**Comment by glittershark** [comment]
@cumbreras just pushed 0.11.0

**Comment by cumbreras** [comment]
@glittershark thanks for keeping the awesome flowing!

**Comment by thientran1707** [comment]
@glittershark the Paginator is reactable Paginator?

**Comment by glittershark** [comment]
I'm not sure what you're asking

**Comment by thientran1707** [comment]
<Table ...>
    ...
    <Paginator>
        <a className="btn btn-default" />
    </Paginator>
</Table>

I found this in #4. In the doc, it's <Table .../>. I do not know how to style the paginator

**Comment by thientran1707** [comment]
I would like to style the paginator with Bootstrap. #4  does not mention how to do it? And in the doc, it also does not show how to change the styling. Somehow I can change the style of paginator?

**Comment by glittershark** [comment]
#4 is an issue to add the ability to customize the class of the paginator. FWIW you can do it right now by just using a CSS preprocessor or copy-paste to style the classes we use using Bootstrap's styles

**Comment by thientran1707** [comment]
oh I see. Thanks. I think that you will attach css file

**Comment by thientran1707** [comment]
oh... I see. Thanks

**Comment by thientran1707** [comment]
@glittershark when I change the version in package.json to 0.11.0, it tells my that "Error: Cannot find module './stringable' " . I tried rm -rf node_modules and reinstalled but it does not solve the problem.

**Comment by glittershark** [comment]
Sounds like a dupe of #167

**Pull request merged**
