### PR TITLE
Bound onClick handler to this

### PR DESCRIPTION
**Pull request by KendallPark**
resolves: https://github.com/glittershark/reactable/issues/157

### CODE REVIEW

**Comment by glittershark** [comment]
Cool, thanks! This is why I did the latest version as a beta first. Thanks for testing on the bleeding edge! :wink:

**Comment by KendallPark** [comment]
NP. :beers:

**Comment by glittershark** [comment]
Alright, wrote some tests then merged this as 179e42291b511841ac5b43cb92233c2da31d934e

**Comment by KendallPark** [comment]
:+1:

**Pull request closed without merging**
