### PR TITLE
On receiving new props, use defaultSort if sortBy is false

### PR DESCRIPTION
**Pull request by tjphopkins**
If columns have changed on receiving new props, this.state.currentSort
may reference a column which no longer exists. It should then be
updated to nextProps.defaultSort if it exists.

### CODE REVIEW

**Comment by glittershark** [comment]
Can you add a test covering this please?

**Comment by tjphopkins** [comment]
I have a test for this but it works using new code in my other PR: https://github.com/glittershark/reactable/pull/298 , so I'll wait for that to be merged. Thanks

**Comment by tjphopkins** [comment]
I think this is ready :)

**Comment by tjphopkins** [comment]
@glittershark Hi. I'm running this in production now and would love to get this merged upstream. Thanks!

**Pull request closed without merging**
