### PR TITLE
Fixed duplicate ReactableTestUtils and added test for className being passed to Tr

### PR DESCRIPTION
**Pull request by rtsao**
This test demonstrates that https://github.com/glittershark/reactable/issues/100 is still an issue.

### CODE REVIEW

**Comment by rtsao** [comment]
Test to show that https://github.com/glittershark/reactable/issues/100 is still an issue.

**Comment by rtsao** [comment]
Build should fail due to failed test

**Comment by glittershark** [comment]
Thanks for this!

**Comment by glittershark** [comment]
I fixed this. Thanks again for the tests!

**Pull request merged**
